#!/bin/bash

# Compose varnish startup command
STARTUP_CMD="varnishd -s malloc,100M \
-a ${VARNISH_HOST}:${VARNISH_PORT} \
-T ${VARNISH_CLI_HOST}:${VARNISH_CLI_PORT}"

if [ ${VARNISH_BACKEND_HOST} ]; then
	STARTUP_CMD="${STARTUP_CMD} -b ${VARNISH_BACKEND_HOST}:${VARNISH_BACKEND_PORT}"
else
	STARTUP_CMD="${STARTUP_CMD} -f /etc/varnish/default.vcl"
fi

# Start varnish
$STARTUP_CMD

# Start logging
varnishlog